# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c6e9b17a148bb4a6d7417531e5ab1a31241425b461304dccaf4f7dfcb929b7fd535500f302c6602d2172abfc0f41516f932e8bcb66af8ded24faebdf8ad35e

test:
  secret_key_base: 77fdf9981fef30974f22924641e0902dd369643f5b2bf47b0e9fdb5cc31d48b142284a390bb2e73ccb7bed5dc06e8ca24f66a80bc0eed74b1b5779de5f1b7ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
